# build settings
sass:
    style: compressed

# site settings
lang: ja
charset: utf-8
title: denvernine
description: you're under my control.
timezone: Asia/Tokyo
since: '2019-12-24 18:00'
icons:
    - type: icon
      mime_type: image/x-icon
      path: /assets/images/favicon.ico
      size: 16x16
    - type: apple-touch-icon
      mime_type: image/png
      path: /assets/images/apple-touch-icon.png
      size: 256x256
email: denvernine99@gmail.com
phone: +818084115920
twitter_username: nkiril
github_username:  denvernine

# page settings
permalink: /:categories/:year:month:day-:slug:output_ext
defaults:
    - scope:
        path: ''
        type: pages
      values:
        layout: base
        meta_twitter: true
