# build settings
sass:
    style: compressed

# site settings
lang: ja
direction: ltr
charset: UTF-8
timezone: Asia/Tokyo
title: denvernine.
description: &description you're under my control.
since: 2019-12-24
icon:
  type: icon
  mime_type: image/x-icon
  path: /assets/images/favicon.ico
  size: 16x16
email: denvernine99@gmail.com
phone: +818084115920
twitter_username: nkiril
github_username:  denvernine
related_post_count: 5

# page settings
permalink: /:year/:month/:day/:title
defaults:
    - scope:
        path: ''
        type: pages
      values:
        layout: default
        description: *description
    - scope:
        path: ''
        type: posts
      values:
        layout: default
        description: *description
