name: update gist list
on:
  schedule:
  - cron: "11 5 * * 1"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - id: step_one
      name: switch branch
      uses: actions/checkout@master
    - id: step_two
      name: update gist list
      uses: sergeysova/jq-action@v2.1.0
      with:
        cmd: |
          curl -sSL -H 'Accept: application/vnd.github.v3+json' -- 'https://api.github.com/users/denvernine/gists?per_page=5&page=1' \
          | jq '.[] | { title: .description, updated_at: .updated_at, url: .html_url }' \
          > _data/posts.yaml
