name: update gist list
on:
  schedule:
  - cron: "11 5 * * 1"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - id: step_one
      name: switch branch
      uses: actions/checkout@v3
    - id: step_two
      name: get gist list
      run: |
        curl -sSL -H 'Accept: application/vnd.github.v3+json' -- 'https://api.github.com/users/denvernine/gists?per_page=5&page=1' \
        > _data/gists.json
    - id: step_three
      name: update gist list
      uses: mikefarah/yq@v4.24.2
      with:
        cmd: |
          yq '.[] | [{ "title": .description, "updated_at": .updated_at, "url": .html_url }]' -- _data/gists.json \
          > _data/gists.yaml
    - id: step_four
      name: push gist list
      run: |
        git config user.name denvernine
        git config user.email denvernine99@gmail.com
        git add _data/gists.yaml
        git commit -m "update gist list"
        git push
